"""Rename city to location

Revision ID: 12d42f2bd6bc
Revises: 
Create Date: 2026-05-10 08:28:59.679637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d42f2bd6bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('universities', 'city', new_column_name='location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('universities', 'location', new_column_name='city')
    # ### end Alembic commands ###
