"""add_programme_website_url

Revision ID: 3017614a0b36
Revises: f3166476c896
Create Date: 2026-05-25 12:25:01.160724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3017614a0b36'
down_revision = 'f3166476c896'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programmes', sa.Column('programme_website_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programmes', 'programme_website_url')
    # ### end Alembic commands ###
