"""Refactor requirements

Revision ID: 7d35d9cf3855
Revises: d1862a72f304
Create Date: 2026-05-20 12:01:09.463508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d35d9cf3855'
down_revision = 'd1862a72f304'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programmes', sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('programmes', 'math_ects_required')
    op.drop_column('programmes', 'miscellaneous_criteria')
    op.drop_column('programmes', 'credits_breakdown')
    op.drop_column('programmes', 'cs_ects_required')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programmes', sa.Column('cs_ects_required', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('programmes', sa.Column('credits_breakdown', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('programmes', sa.Column('miscellaneous_criteria', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('programmes', sa.Column('math_ects_required', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('programmes', 'requirements')
    # ### end Alembic commands ###
