"""Add tuition fee columns

Revision ID: 86120ad2b0df
Revises: a3f8c1d2e4b5
Create Date: 2026-05-10 12:29:20.500048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86120ad2b0df'
down_revision = 'a3f8c1d2e4b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programmes', sa.Column('is_free_tuition', sa.Boolean(), nullable=True))
    op.add_column('programmes', sa.Column('tuition_fee', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programmes', 'tuition_fee')
    op.drop_column('programmes', 'is_free_tuition')
    # ### end Alembic commands ###
