"""add teaching_language column

Revision ID: d1862a72f304
Revises: 86120ad2b0df
Create Date: 2026-05-20 11:52:58.937999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1862a72f304'
down_revision = '86120ad2b0df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programmes', sa.Column('teaching_language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programmes', 'teaching_language')
    # ### end Alembic commands ###
