"""Update gre_required to String

Revision ID: f3166476c896
Revises: 7d35d9cf3855
Create Date: 2026-05-24 10:02:01.173336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3166476c896'
down_revision = '7d35d9cf3855'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('programmes', 'primary_teaching_language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.execute("ALTER TABLE programmes ALTER COLUMN gre_required DROP DEFAULT;")
    op.execute("ALTER TABLE programmes ALTER COLUMN gre_required TYPE VARCHAR USING CASE WHEN gre_required=true THEN 'Advisable' ELSE 'Not Required' END;")
    op.execute("ALTER TABLE programmes ALTER COLUMN gre_required SET DEFAULT 'Not Required';")
    op.alter_column('programmes', 'gre_required',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('programmes', 'tuition_fee_per_semester',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('programmes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('programmes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('universities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('universities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('universities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('universities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('programmes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('programmes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('programmes', 'tuition_fee_per_semester',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=7, scale=2),
               existing_nullable=True)
    op.execute("ALTER TABLE programmes ALTER COLUMN gre_required DROP DEFAULT;")
    op.execute("ALTER TABLE programmes ALTER COLUMN gre_required TYPE BOOLEAN USING CASE WHEN gre_required='Advisable' OR gre_required='Mandatory' THEN true ELSE false END;")
    op.execute("ALTER TABLE programmes ALTER COLUMN gre_required SET DEFAULT false;")
    op.alter_column('programmes', 'gre_required',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('programmes', 'primary_teaching_language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
